name: Build EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # הורדת קוד
      - name: Checkout code
        uses: actions/checkout@v2

      # התקנת Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # התקנת תלויות
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # בדיקת קבצים במאגר
      - name: Check files in repository
        run: |
          echo "Current directory:"
          pwd
          echo "Files in directory:"
          ls -l

      # בניית קובץ EXE
      - name: Build executable with PyInstaller
        run: pyinstaller --onefile main.py

      # העלאת הקובץ שנוצר
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: main-exe
          path: dist/main
