name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # שלב 1: הורדת הקוד
      - name: Checkout code
        uses: actions/checkout@v3

      # שלב 2: התקנת Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # שלב 3: התקנת תלויות
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # שלב 4: בדיקת קבצים
      - name: Check files in repository
        run: |
          echo "Current directory:"
          pwd
          echo "Files in directory:"
          ls -l

      # שלב 5: בנייה ל-EXE
      - name: Build executable with PyInstaller
        run: pyinstaller --onefile main.py

      # שלב 6: העלאת קובץ EXE שנבנה
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: main-exe
          path: dist/main
