name: Build EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # שלב 1: הורדת הקבצים מהמאגר
      - name: Checkout code
        uses: actions/checkout@v2

      # שלב 2: הגדרת סביבת Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # שלב 3: התקנת התלויות
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # שלב 4: בדיקת מיקום קבצים
      - name: Check file existence
        run: |
          echo "Current Directory:"
          pwd
          echo "Files in directory:"
          ls -alh
          echo "Does main.py exist?"
          ls main.py || echo "main.py not found!"

      # שלב 5: בניית הקובץ ל-EXE
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile main.py

      # שלב 6: שמירת הקובץ שנבנה כארטיפקט
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: main-exe
          path: dist/main
