name: Build for Multiple Platforms

on:
  push:
    branches:
      - main  # או כל סניף אחר שאתה רוצה

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build EXE using PyInstaller (Windows)
        run: |
          pyinstaller --onefile --distpath dist/windows --workpath build/windows main.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-exe
          path: dist/windows/main.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build binary using PyInstaller (Linux)
        run: |
          pyinstaller --onefile --distpath dist/linux --workpath build/linux main.py

      - name: Upload Linux binary artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-bin
          path: dist/linux/main

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build .app using PyInstaller (macOS)
        run: |
          pyinstaller --onefile --distpath dist/macos --workpath build/macos main.py

      - name: Upload macOS .app artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos-app
          path: dist/macos/main.app
